### PR TITLE
Audio

### PR DESCRIPTION
**Pull request by poetaster**
I'm not sure this is of any interest to you, but I've implemented an Initial basic TurtleAudio class and use it with Turtle to explore  some sonification. 

If you don't have time or interest no thing. I'm more of a supercolider guy, but I wanted to learn a bit about the web audio apis.

I have one issue at the moment and that is creating (suspending and resuming) the initial AudioContext. I've tried beginning with LSystem (where it's passed on in from Turtle to TurtleAudio), but that's wrong. There always appears to be one extra initial AudioContext running. I was hoping that the dispose methods would get me there. Any insight as to where (probably 'createScene'?) I should be setting up and stop starting would be appreciated!

Thanks and regards,

Mark

PS:  I did a bunch of sonifications with supercollider: 
https://github.com/poetaster/supercollider-lsystems https://poetaster.de/sc-ls/ which go me going on this.

### CODE REVIEW

**Comment by anvaka** [comment]
This is super cool! When I try it locally - the entire composition goes wooosh - much faster than https://poetaster.de/sc-ls/ - do I need to change something to make it sound similar?

btw, this could be great priming source to https://huggingface.co/spaces/facebook/MusicGen - this one is `trance with deep bass` :)

https://github.com/anvaka/lsystem/assets/225407/a917ea75-791f-4445-a3ff-71017b75da70


Just check this one out

**Comment by poetaster** [comment]
> This is super cool! When I try it locally - the entire composition goes wooosh - much faster than https://poetaster.de/sc-ls/ - do I need to change something to make it sound similar?

Do you mean the super collider files or the initial browser based sketch here? The SC files all set the clock rate:
```
	// up the rate a bit
	TempoClock.default = TempoClock.new(1);
```
Which is the global rate.  If it's too fast in SC, set  TempoClock.new(0.5); for instance. 

For the web version, I still have to build instruments, this is just an initial sketch to get started. And I couldn't get rid of the doubled AudioCtx (which means you always have a background hum).


> btw, this could be great priming source to https://huggingface.co/spaces/facebook/MusicGen - this one is `trance with deep bass` :)
> tmpudhgxcyf.mp4
> 
> Just check this one out

Hah! What I was going for is automagic Ragas (the India Carnatic Music System). But that is very suitable material for Trance, for sure! I haven't looked at MusicGen yet, but I've built my own neural net instruments before. I'll go have a look ! The approach here is kinda primitive but has the advantage that the rules for generating more or less complex images runs parallel to the production of the music, so you get generative audiovisuals from simple rules. 

It might interest you, if you hadn't already seen it, here's another approach to algo composition in the browser: https://alexcrist.github.io/scaler/

**Comment by poetaster** [comment]
Ah, one more thing, I hadn't gotten the drawing and audio generation running in parallel in SC because of factors like the number of generations leading to really long audio tracks, but also cause I just got caught up in the musical bits. Some of the audio is generated with so few generations that the resulting image would be 'paltry'. But that's the fun of it all.

**Comment by anvaka** [comment]
I'm very far from audio generation and audio APIs, but this looks very interesting. Still trying to understand your change here - I see you've got 2 oscillators,  there is `updateWave()` and `setChord()` (doesn't seem to be used).

If I read it correctly, this is the core of how audio is generated:

```
    this.turtleAudio.freq1 = this.turtleAudio.freq1 + (distance * n[0]) ;
    if ( this.turtleAudio.freq1 > 1000 )
      this.turtleAudio.freq1 = 138.5 
    this.turtleAudio.updateFreq1();
```

Sorry for the naive question: how this frequency update translates to sound?

**Comment by poetaster** [comment]
> Sorry for the naive question: how this frequency update translates to sound?

Not at all naive, it's still naive code :) here the previous frequency is modified by first vectors motion * distance. So, you just get a rising, falling frequency (or no change) with movement. In my supercollider patches I did this with the primitives, which is more difficult (still) here.

I use +-fxy and so on directly in the sc context. Here I had just started playing with freq up down with angle and motion changes. I had started to test picking notes from ascending/descending scales, but had only started. The background instance was driving me batty. One can also introduce all kinds of heuristics as a product of changes.

One could think of lots of variations, but in principle you always have directed motion in patterns. like chords played in alternating fifths chords up and down. 

In the sc context I also use different instruments. Here we only have a sawtooth and a sinus wave osc.

**Comment by poetaster** [comment]
I helps sometimes to have the right starting point. Try:
```
  // P. Bourke after Saupe
axiom: VZFFF
rules:
  V -> [+++W][---W]YV
  W -> +X[-W]Z
  X -> -W[+X]Z
  Y -> YZ
  Z -> [-FcFF][+FdFF]F

color: green
depth:10
direction: [0, 1, 0]
angle: 20
actions:
  c => setColor('lightgreen')
  d => setColor('lime')
```

It's different drawing to the left or right.

**Comment by poetaster** [comment]
Sigh, sorry for so much content. I've had to revert to attaching the AudioContext to window. But even then calling suspend/resume is flaky as 'dispose' doesn't seem to be called on completion of rendering. So even with only one global audio context exists, one can't reliably turn it on and off. I'm looking at building this differently.

**Comment by poetaster** [comment]
One more note. I was going at this from the 'lowest' level. It might make more sense to look at using https://tonejs.github.io/ which already has a number of instrument models and ADSR (volume envelopes) and so on ....

**Comment by poetaster** [comment]
Sooo, I've begun with tone.js: https://github.com/poetaster/lsystem/tree/tonejs

The big issue here is how to get createScene / LSystem to draw in the audio context.

```
		const loop = new Tone.Pattern(((time, note) => {
			synth.triggerAttackRelease(note, "16n", time);

			// Draw.schedule takes a callback and a time to invoke the callback
			Tone.Draw.schedule(() => {
				// the callback synced to the animation frame at the given time
				const noteElement = document.querySelector("#"+note);
				noteElement.classList.add("active");
				setTimeout(() => {
					noteElement.classList.remove("active");
				}, 100);
			}, time);
		}), ["C4", "E4", "G4", "B4", "D5"]).start(0);
```
This simple example shows directly turning on an off an element class to animate. I'm wondering what the best way is to implement a callback in 'createScene' so that the raf takes place on demand?

**Comment by anvaka** [comment]
Sorry I'm not familiar with tone.js. Do I understand correctly that you are trying to have one animation frame to be executed only after the note has done playing?

**Comment by poetaster** [comment]
> Sorry I'm not familiar with tone.js. Do I understand correctly that you are trying to have one animation frame to be executed only after the note has done playing?

The duration of the entire animation has to 'make sense' in terms of the musical time. That means, not frame to note per se, but that the the rate at which frames are drawn depends on the duration of the sounds that are made while that move/draw/rotate effect a change in the sequence of tones/notes/sounds. You can speed up the rate at which sounds are made, but if you link the drawing directly to sound, you have to give one precedence. If you let the drawing determine the rate of change, as is seen with this pull, it's a really fast 'blip'. If you defer frame rendering to a queue that depends on the duration of the sounds for each 'tick' of system, the drawing 'follows' the sound. But just have a look at:
https://tonejs.github.io/examples/animationSync 

The main point with tone.js is that it has a bunch of primitives that make it much easier for you to grok, without my mucking about with 'realy' primitive basics. Instuments, sequences, patterns,  a Transport. What I was doing here was with real primitives. But in the end, I'll have to add a ton of layers anyway, and tone does that quiet well, though it's a bit heavy.  I'll just try to get this to a point where it's easier for you. Sorry for noise to signal ratio!

**Comment by poetaster** [comment]
Man am I long winded.

 It would certainly also be possible to just do as I've done in this context with  calls in Turtle.js to play like ``` conga.triggerAttack(pitch, time, Math.random()*0.5 + 0.5);```  if you slow the frame rate down.

**Comment by poetaster** [comment]
This is a first take with the synth triggering still taking place in Turtle.js  but using actual instruments.... https://github.com/poetaster/lsystem/tree/tonejs

I'm going to close this PR since, even if I return to a simplified method, it'll look completely different.

If you have a chance take a look at that other branch for an idea of how Tone.js can be used. I need to brood on this for a while since it's a a LOT more finicky than working with supercollider (or pd or c++ :)

**Pull request closed without merging**
